def basic_op(operator, value1, value2):
    if (operator == '+'):
            return value1 + value2;
    if (operator == '-'):
            return value1 - value2;
    if (operator == '*'):
            return value1 * value2;
    if (operator == '/'):
            return value1 / value2;